// This layout page will define the layout and component for the web pages
import '@/styles/globals.css'
import Header from './Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Dai's Website</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
